{
    'name': 'JI Asset',
    'version': '17.0.1.0',
    'category': 'Invoicing Management',
    'description': '固定資產功能 ',
    'summary': '固定資產功能',
    'author': 'JI ',
    'license': 'Other proprietary',
    'company': 'JI',
    'maintainer': 'JI',
    'support': '',
    'website': '',
    'depends': ['account', 'product', 'base'],
    'data': [
         'data/imp_asset_config.xml',
         'data/imp_ir_sequence.xml',
         'security/ir.model.access.csv',
         'report/asset_depreciation_report_template.xml',
         'report/asset_master_report_template.xml',
         'views/asset_config.xml',
         'views/asset_category.xml',
         'views/asset_master.xml',
        #  'views/product_category.xml',   #錯誤
        #  'views/account_move.xml',  #錯誤
         'views/asset_depreciation.xml',
         'views/asset_exe_depreciation_wizard.xml',
         'views/asset_reverse_depreciation_wizard.xml',
         'views/asset_disposal.xml',
         'views/asset_adjust.xml',
         'views/asset_sale.xml',
         'views/asset_depreciation_report.xml',
         'views/asset_master_report.xml',
         'views/menu_item.xml',
    ],
    'installable': True,
    'application': True,
}